[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rusted_dex = "5sRS7S7T8CR4LfeqHYJSBw1smKoeNmEEM3XLP1jhcLGZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"